project:
  type: website
  output-dir: docs


website:
  title: "Operationalizing CTmax"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

